### ISSUE TITLE
ModuleNotFoundError: No module named 'gentle'

### ISSUE THREAD

**Issue by zf223669** [ai4r/SGToolkit#2]
Dear Sir:
    When i runned  "python waitress_server.py"
     One error showed below:
(sgtoolkit) PS D:\GestureSynthesisProjects\SGToolkit\gentle> python waitress_server.py
Traceback (most recent call last):
  File "waitress_server.py", line 2, in <module>
    import app
  File "D:\GestureSynthesisProjects\SGToolkit\gentle\app.py", line 4, in <module>
    import sg_core_api as sgapi
  File "D:\GestureSynthesisProjects\SGToolkit\gentle\sg_core_api.py", line 29, in <module>
    from sg_core.scripts.gesture_generator import GestureGenerator
  File "D:\GestureSynthesisProjects\SGToolkit\gentle\sg_core\scripts\gesture_generator.py", line 14, in <module>
    import gentle
ModuleNotFoundError: No module named 'gentle'

How could I fixed?
Thank you !

**Comment by youngwoo-yoon** [comment]
Hello,
Gentle does not work in Windows. There are some related issues in the gentle repository: https://github.com/lowerquality/gentle. 
You could try WSL2 in Windows 10.

**Comment by zf223669** [comment]
Thank you for your reply.   Could I ask another question/
Which is the Python version you use?
Thanks!

**Comment by youngwoo-yoon** [comment]
Sure, I tested on Ubuntu 18.04 and Python 3.6.

**Comment by zf223669** [comment]
Hello, I have built the project in ubuntu with Python 3.6 successful, but, I invoke the instruct:"python3 waitress_server.py" and an error showed below:
loading checkpoint /home/zhangfan/SGToolkit/sg_core/output/sgtoolkit/multimodal_context_checkpoint_best.bin
Traceback (most recent call last):
  File "waitress_server.py", line 2, in <module>
    import app
  File "/home/zhangfan/SGToolkit/app.py", line 15, in <module>
    gesture_generator = sgapi.get_gesture_generator()
  File "/home/zhangfan/SGToolkit/sg_core_api.py", line 35, in get_gesture_generator
    return GestureGenerator(model_file_name, audio_cache_path)
  File "/home/zhangfan/SGToolkit/sg_core/scripts/gesture_generator.py", line 28, in __init__
    checkpoint_path, device)
  File "/home/zhangfan/SGToolkit/sg_core/scripts/utils/train_utils.py", line 146, in load_checkpoint_and_model
    checkpoint = torch.load(checkpoint_path, map_location=_device)
  File "/home/zhangfan/miniconda3/envs/sgtoolkit/lib/python3.6/site-packages/torch/serialization.py", line 595, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/zhangfan/miniconda3/envs/sgtoolkit/lib/python3.6/site-packages/torch/serialization.py", line 764, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.

did you meet this problem?

**Comment by youngwoo-yoon** [comment]
Could you try with this file? This goes to the /sg_core/output folder.
https://www.dropbox.com/s/b5rwtn60j4tf2vr/multimodal_context_checkpoint_best.bin?dl=0

The file is the same with the one in the current repository, but I suspect the file is not properly uploaded or downloaded via Git LFS.

**Comment by zf223669** [comment]
Done！
Thank you！

**Comment by zf223669** [comment]
Hi, now I could execute the "python waitress_server.py" code and get into the system in Google Chrome, it showed work in the web browse, however, in console it showed a error:
(sgtoolkit) zhangfan@zf:~/SGToolkit$ python3 waitress_server.py
loading checkpoint /home/zhangfan/SGToolkit/sg_core/output/sgtoolkit/multimodal_context_checkpoint_best.bin
{'config': '../config/multimodal_context_toolkit.yml', 'name': 'multimodal_context', 'train_data_path': '../data/ted_dataset_2020.07/lmdb_train', 'val_data_path': '../data/ted_dataset_2020.07/lmdb_val', 'test_data_path': '../data/ted_dataset_2020.07/lmdb_test', 'model_save_path': '../output/temp', 'pose_representation': '3d_vec', 'pose_norm_stats_path': None, 'pose_representation_path': None, 'mean_dir_vec': [[-0.00225], [-0.98496], [0.16212], [0.01831], [-0.79641], [0.52568], [0.02496], [-0.65216], [-0.67807], [-0.87815], [0.40211], [-0.06526], [-0.38831], [0.85245], [0.13283], [0.35888], [-0.16606], [0.7072], [0.87728], [0.41491], [-0.00166], [0.38441], [0.85739], [0.14593], [-0.39277], [-0.17973], [0.69081]], 'mean_pose': [[-0.0], [-2e-05], [4e-05], [-0.00055], [-0.24976], [0.03882], [0.00152], [-0.32251], [0.10291], [0.0043], [-0.43652], [0.02527], [-0.12537], [-0.19055], [0.03108], [-0.23547], [0.04413], [0.06726], [-0.14551], [0.00403], [0.23596], [0.12585], [-0.18445], [0.04031], [0.23547], [0.04749], [0.08014], [0.13293], [0.00299], [0.24744]], 'style_val_max': [[0.01574225], [1.5461352], [1.0]], 'style_val_mean': [[0.00241791], [0.48645255], [0.0]], 'style_val_std': [[0.00120855], [0.17992376], [1.0]], 'random_seed': 0, 'save_result_video': True, 'wordembed_path': '../data/fasttext/crawl-300d-2M-subword.bin', 'wordembed_dim': 300, 'freeze_wordembed': False, 'model': 'multimodal_context', 'epochs': 80, 'batch_size': 128, 'dropout_prob': 0.3, 'n_layers': 4, 'hidden_size': 300, 'residual_output': False, 'z_type': 'style_vector', 'input_context': 'both', 'use_pose_control': True, 'use_style_control': True, 'motion_resampling_framerate': 15, 'n_poses': 60, 'n_pre_poses': 30, 'subdivision_stride': 20, 'normalize_motion_data': True, 'augment_data': False, 'loader_workers': 4, 'GAN_noise_size': 0, 'diff_augment': True, 'learning_rate': 0.0005, 'discriminator_lr_weight': 0.2, 'loss_l1_weight': 500.0, 'loss_gan_weight': 5.0, 'loss_reg_weight': 0.05, 'loss_warmup': 10, 'eval_net_path': '../output/h36m_gesture_autoencoder/gesture_autoencoder_checkpoint_best.bin'}
Serving on http://0.0.0.0:8080
**ERROR:app:Exception on /api/motion [GET]
Traceback (most recent call last):
  File "/home/zhangfan/miniconda3/envs/sgtoolkit/lib/python3.6/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/zhangfan/miniconda3/envs/sgtoolkit/lib/python3.6/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/zhangfan/miniconda3/envs/sgtoolkit/lib/python3.6/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/zhangfan/miniconda3/envs/sgtoolkit/lib/python3.6/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/zhangfan/SGToolkit/app.py", line 40, in motion_library
    cursor = mongo.db.motion.find().sort("name", 1)
AttributeError: 'NoneType' object has no attribute 'motion'
ERROR:app:Exception on /api/rule [GET]
Traceback (most recent call last):
  File "/home/zhangfan/miniconda3/envs/sgtoolkit/lib/python3.6/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/zhangfan/miniconda3/envs/sgtoolkit/lib/python3.6/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/zhangfan/miniconda3/envs/sgtoolkit/lib/python3.6/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/zhangfan/miniconda3/envs/sgtoolkit/lib/python3.6/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/zhangfan/SGToolkit/app.py", line 80, in rule
    cursor = mongo.db.rule.aggregate(pipeline)
AttributeError: 'NoneType' object has no attribute 'rule'**

**Comment by youngwoo-yoon** [comment]
It is now fixed by handling exceptions.
